Increase the maximum size of event data
particle-iot/device-os pull request #2260
Opened 2020-12-24 18:29 UTC by sergeuz

WIP

2021-02-08 18:29 UTC, sergeuz commented
I just realized that we can't make this change for Electron due to limitations of the socket layer on that platform. I'll update this PR accordingly.

2021-02-17 14:11 UTC, sergeuz commented
I decreased the maximum size from 1024 to 864 bytes on Gen 2 platforms and added integration tests. This PR should be ready for review now, @avtolstoy.

2021-03-09 19:55 UTC, avtolstoy requested changes

2021-03-09 20:01 UTC, sergeuz commented on communication/src/protocol.cpp
> +		d.maxBinarySize(ota_chunk_size);
Fixed :pray:

2021-03-09 20:02 UTC, avtolstoy approved these changes

2021-03-10 02:19 UTC, merged