Panic handler updates
particle-iot/device-os pull request #2384
Opened 2021-12-22 23:41 UTC by mrlambchop

Add in the ability to override the panic handler to change the behaviour of assert/panic in the system

<details>
<summary>
<I>
- add in dynalib binding for user space apps (unstable API)
- refactor some of the panic code that wasn't being used
</I>
</summary>
</details>

### Problem

Applications want to have the ability to override the panic handler such that customer panic handlers can be implemented in user space.

### Solution

Add in panic_hook_set() function and dynalib bindings

2021-12-23 00:01 UTC, avtolstoy requested changes
Mainly `panic_set_override` needs to have a `void* reserved` argument to allow for extensibility.

2021-12-23 00:01 UTC, avtolstoy commented on services/inc/panic.h
> +void panic_set_override(const PanicHook panicHook);
I propose we also wrap this function under `#if !defined(PARTICLE_USER_MODULE) || defined(PARTICLE_USE_UNSTABLE_API)` similar to `storage_hal.h`, to indicate that this is not a stable API and you should explicitly enable it with `PARTICLE_USE_UNSTABLE_API` and unrerstand what you are doing.

2021-12-23 00:16 UTC, avtolstoy commented on services/inc/logging.h
> -            panic_(_code, NULL, HAL_Delay_Microseconds); \
A second thought/result of private discussion: this needs to be kept as-is for Photon/P1/Electron. The problem is that services dynalib exists in system-part1 and timer_hal implementation in part2. This is the opposite way of the dependency tree, the imports go from part1 into part2 into user app, hence why the pointer to micros function is passed here. Fine on other platforms, but going cause issues for Gen 2.

2021-12-23 08:12 UTC, elcojacobs commented
Nice to see this picked up. I would like to see a possibility to store a hardfault address in backup ram so it can be sent to a log and doesn't require a hardware debugger to capture. This however happens before the panic handler is called. Is this possible?

2021-12-28 04:27 UTC, avtolstoy requested changes

2021-12-28 04:27 UTC, avtolstoy commented on services/src/panic.c
> +static PanicHook panicHook = panic_internal;
This should be `nullptr` after refactoring, otherwise we'll run `panic_internal` twice.

2021-12-28 04:27 UTC, avtolstoy commented on services/inc/services_dynalib.h
> +DYNALIB_FN(BASE_IDX + 4, services, panic_set_hook, void(PanicHook, void*))
Signature does not match what's in `panic.h` (`const` vs non-`const` `PanicHook`)

2021-12-28 13:59 UTC, avtolstoy approved these changes

2022-01-31 20:51 UTC, elcojacobs commented
Can you pass the register info extracted in prvGetRegistersFromStack to the panic hook?
That would make it possible to actually get some useful info on the panic location in code, instead of just some different LED behaviour or just logging the panic reason.

Getting a log of the panic reason is already possible through the reset reason that is stored in backup RAM.

2022-01-31 21:10 UTC, merged

2022-02-01 19:36 UTC, elcojacobs commented
I am not using the Particle cloud and I don't want to use it for publishing errors either. So please keep the mechanisms open, so I can report the error to a local server too.

2022-05-04 10:28 UTC, perotom commented
> Hey elcojacobs, plan is (a) implement the panic handler (b) test using this repo to capture / report bugs (https://github.com/particle-iot/errorflinger-library) (c) add in stack retrieval functions on a crash (d) release this in conjunction with a partnership with memfault.io as a third party crash analysis tool. Feedback welcome on the strategy!

Sounds great. I am with @elcojacobs: would be great if these mechanisms are open for writing these information to SD card or showing them on a display on reboot.