Gen2 supply secure
particle-iot/device-os pull request #2442
Opened 2022-04-21 18:03 UTC by keeramis

### Description

Gen 2 supply secure

Platforms - Photon/P1/Electron

### Solution

N/A

### Steps to Test

N/A

### References

[SC-100649](https://app.shortcut.com/particle/story/100649/gen2-supply-secure-device-os-4-x)

---

### Completeness

- [x] User is totes amazing for contributing!
- [ ] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [ ] Problem and Solution clearly stated
- [ ] Run unit/integration/application tests on device
- [ ] Added documentation
- [ ] Added to CHANGELOG.md after merging (add links to docs and issues)

2022-04-29 15:52 UTC, XuGuohui requested changes

2022-04-30 15:24 UTC, technobly commented on hal/inc/spi_hal.h
> -#if PLATFORM_ID == PLATFORM_ELECTRON_PRODUCTION
I changed this to:
```
/* Exported types ------------------------------------------------------------*/
typedef enum hal_spi_interface_t {
    HAL_SPI_INTERFACE1 = 0,    // maps to SPI (pins: A3, A4, A5)
    HAL_SPI_INTERFACE2 = 1,    // maps to SPI1 (pins: D4, D3, D2)
    HAL_SPI_INTERFACE3 = 2     // maps to SPI2 (pins: ?, ?, ?)
} hal_spi_interface_t;
```

2022-04-30 15:26 UTC, technobly commented on hal/inc/usart_hal.h
> -#if PLATFORM_ID == PLATFORM_ELECTRON_PRODUCTION // Electron
I changed this to:
```
typedef enum hal_usart_interface_t {
    HAL_USART_SERIAL1 = 0,    // maps to USART_TX_RX
    HAL_USART_SERIAL2 = 1,    // maps to USART_RGBG_RGBB
    HAL_USART_SERIAL3 = 2,    // maps to ?
    HAL_USART_SERIAL4 = 3,    // maps to ?
    HAL_USART_SERIAL5 = 4     // maps to ?
} hal_usart_interface_t;
```

2022-04-30 15:28 UTC, technobly commented on communication/src/build.mk
>  ifneq ($(HYBRID_BUILD),y)
Since this appears to be more of a Gen3 thing, I'll open a separate story for it to evaluate.

2022-05-05 13:17 UTC, XuGuohui approved these changes

2022-05-11 17:09 UTC, avtolstoy requested changes

2022-05-11 17:09 UTC, avtolstoy commented on wiring/inc/spark_wiring_wifi.h
> -#endif // !HAL_PLATFORM_NCP
Keep.

2022-05-11 19:20 UTC, technobly commented on bootloader/src/main.c
> -    get_led_theme_colors(&FirmwareUpdateColor, &SafeModeColor, &DFUModeColor);
I'll add HAL_PLATFORM_LED_THEME to hal_platform.h

2022-05-11 19:36 UTC, technobly commented on communication/src/dsakeygen.cpp
> +#include "tropicssl/rsa.h"
Removed all `USE_MBEDTLS` conditionals and code that was defined under `!USE_MBEDTLS`.

2022-05-11 20:05 UTC, technobly commented on crypto/inc/mbedtls_weaken.h
>  #pragma weak mbedtls_to_system_error
Removed `mbedtls_weaken.h` and the code that was including it.  Removed CRYPTO_PART1_SIZE_OPTIMIZATIONS and files that used it like mbedtls_communication.inc and mbedtls_communication.cpp

2022-05-11 21:04 UTC, technobly commented on newlib_nano/src/sources.mk
> +ifneq (,$(filter $(PLATFORM_ID),12 13 22 23 25 26))
I like the first suggestion of using `HAL_PLATFORM_FREERTOS in malloc.cpp` and keeping it modular... I went with this as it's also the simpler change with least impact on code.

2022-05-11 21:25 UTC, technobly commented on user/tests/wiring/no_fixture/uart.cpp
> -#include "Serial2/Serial2.h"
Moved the implementations to `spark_wiring_usarserial.h` and emptied the original headers.

2022-05-11 21:50 UTC, technobly commented on build/version.mk
> +VERSION_STRING = 4.0.0
Reverted now... and created a proper bump in test/v4.0.0-alpha.1 that we can cherry pick back on top for testing after Keerthy pushes some changes for tests.

2022-05-11 22:21 UTC, keeramis commented on user/tests/wiring/api/wiring.cpp
> -    API_COMPILE(attachSystemInterrupt(SysInterrupt_TIM1_CC_IRQ, D0_callback));
@avtolstoy Should we remove `detachSystemInterrupt` as well as a part of this?

2022-05-12 00:00 UTC, keeramis commented on user/tests/wiring/no_fixture/interrupts.cpp
> -#if /* defined(STM32F10X_MD) || defined(STM32F10X_HD) || */ defined(STM32F2XX)
@avtolstoy This is only defined for STM32. Should we make new tests for NRF platform? `SysInterrupt_SysTick` goes away with STM32

2022-05-12 10:17 UTC, avtolstoy commented on user/tests/wiring/no_fixture/interrupts.cpp
> -#if /* defined(STM32F10X_MD) || defined(STM32F10X_HD) || */ defined(STM32F2XX)
We never adjusted it for Gen 3, it's just that. The main thing it's testing is some interrupts_hal functions. Just change it to use `attachInterruptDirect()`:
```c++
        static volatile bool cont = false;
	attachInterruptDirect(SysTick_IRQn, []() {
                detachInterruptDirect(SysTick_IRQn);
		assertTrue(HAL_IsISR());
		assertEqual((IRQn)HAL_ServicedIRQn(), SysTick_IRQn);
		cont = true;
	});
	while (!cont);
	assertFalse(HAL_WillPreempt(SysTick_IRQn, SysTick_IRQn));
	assertTrue(HAL_WillPreempt(NonMaskableInt_IRQn, SysTick_IRQn));
	assertFalse(HAL_WillPreempt(SysTick_IRQn, NonMaskableInt_IRQn));
```

2022-05-12 10:57 UTC, avtolstoy commented on user/tests/wiring/api/wiring.cpp
> -    API_COMPILE(attachSystemInterrupt(SysInterrupt_TIM1_CC_IRQ, D0_callback));
Yes. And the underlying implementation stubs.

2022-05-16 09:36 UTC, avtolstoy approved these changes

2022-05-18 17:42 UTC, merged