Adds support for BG95-M1, BG95-MF, BG77, and EG91-NAX [sc-102979]
particle-iot/device-os pull request #2458
Opened 2022-05-26 05:47 UTC by technobly

### Implements support for BG77, BG95-M1, BG95-MF, and EG91-NAX.

---

### References

#2367 (supersedes this PR due to build error in CircleCI, however refer to any previous comments from that PR before merging)
#2410 (supersedes this PR, to change the branch name)

---

### Completeness

- [x] User is totes amazing for contributing!
- [x] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [x] Problem and Solution clearly stated
- [x] Run unit/integration/application tests on device
- [x] Added documentation
- [ ] Added to CHANGELOG.md after merging (add links to docs and issues)

2022-05-31 18:59 UTC, keeramis commented
ncp needs to be added here as well. 
https://github.com/particle-iot/device-os/blob/feature/sc-102979/hal/shared/platform_ncp.cpp#L29

2022-05-31 18:59 UTC, keeramis requested changes
ncp needs to be added here as well. (edited: If we are keeping `platform_ncp_identifier `)
https://github.com/particle-iot/device-os/blob/feature/sc-102979/hal/shared/platform_ncp.cpp#L29

2022-05-31 23:29 UTC, tstellanova approved these changes

2022-05-31 23:29 UTC, tstellanova approved these changes

2022-06-01 01:13 UTC, keeramis approved these changes
LGTM. Works on BG96 tracker one at my desk as well.

2022-06-01 01:13 UTC, merged