HAL wiring api calls to access exflash read/write functions
particle-iot/device-os pull request #2540
Opened 2022-09-22 07:21 UTC by keeramis

### Description

Adds hal wiring API calls to access OTP

### Solution

Make the relevant functions available over wiring protected by `PARTICLE_USE_UNSTABLE_API`

### Steps to Test

### Example App
```c
#define PARTICLE_USE_UNSTABLE_API
#include "exflash_hal.h"

#include "Particle.h"

void setup() {
  uint8_t ncpId = 0;
  int r = hal_exflash_write_special((hal_exflash_special_sector_t)1 , NCP_ID_OTP_ADDRESS, &ncpId, sizeof(ncpId));
  Log.info("Write result: %d", r);

  r = hal_exflash_read_special((hal_exflash_special_sector_t)1 , NCP_ID_OTP_ADDRESS, &ncpId, sizeof(ncpId));
  Log.info("Read result: %d / %u == %x", r, ncpId, ncpId);
}

void loop() {
}
```

### References

[SC-108936](https://app.shortcut.com/particle/story/108936/spec-way-to-re-provision-p2-device-with-new-provisioning-data)

---

### Completeness

- [x] User is totes amazing for contributing!
- [ ] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [ ] Problem and Solution clearly stated
- [ ] Run unit/integration/application tests on device
- [ ] Added documentation
- [ ] Added to CHANGELOG.md after merging (add links to docs and issues)

2022-09-22 07:31 UTC, avtolstoy requested changes

2022-09-22 07:31 UTC, avtolstoy commented on hal/inc/hal_dynalib_storage.h
> +DYNALIB_FN(3, hal_storage, hal_exflash_read_special, int(hal_exflash_special_sector_t, uintptr_t, uint8_t*, size_t))
This is not really what I've been proposing this week. We don't want to expose low-level flash hal/exflash hal to the application. Such functionality is exposed through an unstable facade API of storage_hal. The idea is that you add `HAL_STORAGE_ID_OTP` and delegate to hal_exflash_xxx_special within `hal_storage_read`/`write` to those.

2022-09-22 19:28 UTC, avtolstoy approved these changes

2022-09-22 19:29 UTC, merged

2022-09-28 05:54 UTC, mohitbhoite commented
As a side, I had to use `SYSTEM_MODE(MANUAL)` otherwise the setup won't execute on an unprovisioned devices, i.e., the new Tracker M boards.

2022-09-28 13:24 UTC, keeramis commented
@mohitbhoite thanks for pointing that out. I will change the example app accordingly.