fix overflow error in HAL_Delay_Microseconds
particle-iot/device-os pull request #2606
Opened 2022-12-19 19:04 UTC by jmwilson

### Problem

`HAL_Delay_Microseconds` on the P2 has this main loop:

```
    system_tick_t start_micros = HAL_Timer_Get_Micro_Seconds();
    system_tick_t current_micros = start_micros;
    system_tick_t end_micros = start_micros + uSec;

    ...

    while (current_micros < end_micros) {
        current_micros = HAL_Timer_Get_Micro_Seconds();
    }
```

If `end_micros` is close to `UINT_MAX` then it is possible that updating `current_micros` can wrap the counter and reset it to a low value, extending the wait by > 71 minutes. The closer `end_micros` is to precisely `UINT_MAX`, the less likely the loop will ever terminate.

### Solution

Check if we've waited long enough by using unsigned difference instead of comparing to `end_micros`. Watchdog isn't implemented yet but is expected later and makes this mirror the nRF code.

### Steps to Test

`wiring/no_fixture` runs without errors.
Run publish in Tracker Edge with sleep enabled to test the startup delay call.

### References

https://app.shortcut.com/particle/story/113600/overflow-in-p2-hal-delay-microseconds-causes-hangs-in-tracker-edge

### Completeness

- [x] User is totes amazing for contributing!
- [ ] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [ ] Problem and Solution clearly stated
- [ ] Run unit/integration/application tests on device
- [ ] Added documentation
- [ ] Added to CHANGELOG.md after merging (add links to docs and issues)

2022-12-19 19:16 UTC, avtolstoy requested changes

2022-12-19 19:16 UTC, avtolstoy commented on hal/src/rtl872x/delay_hal.cpp
> +        HAL_Notify_WDT();
As of #2595 watchdog is not going to be kicked from Device OS, completely under application control. This needs to be removed.

2022-12-19 19:32 UTC, avtolstoy approved these changes

2022-12-20 05:52 UTC, XuGuohui approved these changes

2022-12-20 23:37 UTC, merged