Add WiFi credential check
particle-iot/device-os pull request #2746
Opened 2024-02-28 20:28 UTC by XuGuohui

### Problem

`WiFi.setCredentials()` doesn't verify if the credentials is valid or not.

### Solution

Add a new flag `WLAN_SET_CREDENTIALS_FLAGS_VALIDATE` in WiFi credentials to optionally validate the credentials to be set.

### Steps to Test

Run the `tests/wiring/wifi_cred_check` test

### References

SC125680

---

### Completeness

- [x] User is totes amazing for contributing!
- [x] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [x] Problem and Solution clearly stated
- [ ] Run unit/integration/application tests on device
- [ ] Added documentation
- [ ] Added to CHANGELOG.md after merging (add links to docs and issues)

2024-02-29 12:41 UTC, avtolstoy requested changes

2024-02-29 12:41 UTC, avtolstoy commented on hal/network/ncp/wifi/wlan_hal.cpp
> +    // Note: It's maily a copy of joinNewNetwork() in wifi_new.cpp
Let's have this functionality in a common function then shared by both wlan_hal and `wifi_new.cpp` ?

2024-03-01 13:49 UTC, avtolstoy approved these changes

2024-03-01 14:21 UTC, merged

2024-03-05 00:51 UTC, Kategrode commented
https://app.shortcut.com/particle/story/125680/add-wifi-credential-check